import React, { FC, useCallback, useEffect, useState } from "react";
import styled from "styled-components";
import { Song } from "../../types/Index";
import SongCard from "./SongCard";
import Swipable from "./Swipable";

type Props = {
  token: string;
};

const Container = styled.div`
  background-image: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const Button = styled.button``;

export default function Swiping({ token }: Props) {
  const [cards, setCards] = useState<Song[]>([]);

  const dequeue = (rightSwipped: boolean) => {
    console.log(cards);

    setCards([...cards.slice(1)]);
  };

  const getSong = async () => {
    // const res = await fetch(
    //   `https://api.spotify.com/v1/tracks?ids=7ouMYWpwJ422jRcDASZB7P,4VqPOruhp5EdPBeR92t6lQ,2takcwOaAZWiXQijPHIx7B`,
    //   {
    //     method: "GET",
    //     headers: {
    //       Authorization: `Bearer ${token}`,
    //       Accept: "application/json",
    //       "Content-Type": "application/json",
    //     },
    //   }
    // );

    // const json = await res.json();
    let json: { tracks: Song[] } = {
      tracks: [
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
                },
                href:
                  "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
                id: "12Chz98pHFMPJEknJQMWvI",
                name: "Muse",
                type: "artist",
                uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/0lw68yx3MhKflWFqCsGkIs",
            },
            href: "https://api.spotify.com/v1/albums/0lw68yx3MhKflWFqCsGkIs",
            id: "0lw68yx3MhKflWFqCsGkIs",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/ab67616d0000b27328933b808bfb4cbbd0385400",
                width: 640,
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/ab67616d00001e0228933b808bfb4cbbd0385400",
                width: 300,
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/ab67616d0000485128933b808bfb4cbbd0385400",
                width: 64,
              },
            ],
            name: "Black Holes and Revelations",
            release_date: "2006-06-19",
            release_date_precision: "day",
            total_tracks: 12,
            type: "album",
            uri: "spotify:album:0lw68yx3MhKflWFqCsGkIs",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
              },
              href: "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
              id: "12Chz98pHFMPJEknJQMWvI",
              name: "Muse",
              type: "artist",
              uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 366213,
          explicit: false,
          external_ids: {
            isrc: "GBAHT0500600",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/7ouMYWpwJ422jRcDASZB7P",
          },
          href: "https://api.spotify.com/v1/tracks/7ouMYWpwJ422jRcDASZB7P",
          id: "7ouMYWpwJ422jRcDASZB7P",
          is_local: false,
          name: "Knights of Cydonia",
          popularity: 72,
          preview_url:
            "https://p.scdn.co/mp3-preview/4de2570644eeff4b10cef0770fddfc50e1e2b666?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 11,
          type: "track",
          uri: "spotify:track:7ouMYWpwJ422jRcDASZB7P",
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
                },
                href:
                  "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
                id: "12Chz98pHFMPJEknJQMWvI",
                name: "Muse",
                type: "artist",
                uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/0eFHYz8NmK75zSplL5qlfM",
            },
            href: "https://api.spotify.com/v1/albums/0eFHYz8NmK75zSplL5qlfM",
            id: "0eFHYz8NmK75zSplL5qlfM",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/ab67616d0000b273b6d4566db0d12894a1a3b7a2",
                width: 640,
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/ab67616d00001e02b6d4566db0d12894a1a3b7a2",
                width: 300,
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/ab67616d00004851b6d4566db0d12894a1a3b7a2",
                width: 64,
              },
            ],
            name: "The Resistance",
            release_date: "2009-09-10",
            release_date_precision: "day",
            total_tracks: 11,
            type: "album",
            uri: "spotify:album:0eFHYz8NmK75zSplL5qlfM",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
              },
              href: "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
              id: "12Chz98pHFMPJEknJQMWvI",
              name: "Muse",
              type: "artist",
              uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 304840,
          explicit: false,
          external_ids: {
            isrc: "GBAHT0900320",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/4VqPOruhp5EdPBeR92t6lQ",
          },
          href: "https://api.spotify.com/v1/tracks/4VqPOruhp5EdPBeR92t6lQ",
          id: "4VqPOruhp5EdPBeR92t6lQ",
          is_local: false,
          name: "Uprising",
          popularity: 80,
          preview_url:
            "https://p.scdn.co/mp3-preview/904176ea758e40523f23d0542cfe66423c7caad4?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 1,
          type: "track",
          uri: "spotify:track:4VqPOruhp5EdPBeR92t6lQ",
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
                },
                href:
                  "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
                id: "12Chz98pHFMPJEknJQMWvI",
                name: "Muse",
                type: "artist",
                uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/0HcHPBu9aaF1MxOiZmUQTl",
            },
            href: "https://api.spotify.com/v1/albums/0HcHPBu9aaF1MxOiZmUQTl",
            id: "0HcHPBu9aaF1MxOiZmUQTl",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/ab67616d0000b2738cb690f962092fd44bbe2bf4",
                width: 640,
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/ab67616d00001e028cb690f962092fd44bbe2bf4",
                width: 300,
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/ab67616d000048518cb690f962092fd44bbe2bf4",
                width: 64,
              },
            ],
            name: "Absolution",
            release_date: "2004-03-23",
            release_date_precision: "day",
            total_tracks: 15,
            type: "album",
            uri: "spotify:album:0HcHPBu9aaF1MxOiZmUQTl",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI",
              },
              href: "https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI",
              id: "12Chz98pHFMPJEknJQMWvI",
              name: "Muse",
              type: "artist",
              uri: "spotify:artist:12Chz98pHFMPJEknJQMWvI",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 237039,
          explicit: false,
          external_ids: {
            isrc: "GBCVT0300078",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/2takcwOaAZWiXQijPHIx7B",
          },
          href: "https://api.spotify.com/v1/tracks/2takcwOaAZWiXQijPHIx7B",
          id: "2takcwOaAZWiXQijPHIx7B",
          is_local: false,
          name: "Time is Running Out",
          popularity: 72,
          preview_url:
            "https://p.scdn.co/mp3-preview/b3d0abcaa2a1553347025e98205c9013b61d8391?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 3,
          type: "track",
          uri: "spotify:track:2takcwOaAZWiXQijPHIx7B",
        },
      ],
    };
    setCards(
      cards.length > 0
        ? [...cards, ...json.tracks.filter((card) => card.id != cards[0].id)]
        : [...json.tracks]
    );
  };

  useEffect(() => {
    // console.log(cards);
    if (cards.length <= 1)
      setTimeout(() => {
        getSong();
      }, 300);
  }, [cards]);

  return (
    <>
      <Container className="App">
        {cards.map((card, index) => (
          <Swipable
            key={card.id}
            index={index}
            onTrigger={dequeue}
            triggerDelay={300}
          >
            <SongCard currentSong={card} isOnTop={index == 0} />
          </Swipable>
        ))}
      </Container>
    </>
  );
}

//https://api.spotify.com/v1/tracks/3JcFxUFb4ksMUaAM5LscUb
//3JcFxUFb4ksMUaAM5LscUb
