import React, { useEffect, useState } from "react";
import styled from "styled-components";
import { Song } from "../../types/Song.d";
import SongCard from "./SongCard";
import Swipable from "./Swipable";

type Props = {
  token: string;
};

const Container = styled.div`
  background-image: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const Button = styled.button``;

export default function Swiping({ token }: Props) {
  const [cards, setCards] = useState<Song[]>([]);

  const dequeue = (rightSwipped: boolean) => {
    console.log(
      `you ${rightSwipped ? "liked" : "disliked"} the song ${cards[0].name}`
    );

    setCards([...cards.slice(1)]);
  };

  const getSong = async () => {
    // const res = await fetch(
    //   `https://api.spotify.com/v1/tracks?ids=7ouMYWpwJ422jRcDASZB7P,4VqPOruhp5EdPBeR92t6lQ,2takcwOaAZWiXQijPHIx7B`,
    //   {
    //     method: "GET",
    //     headers: {
    //       Authorization: `Bearer ${token}`,
    //       Accept: "application/json",
    //       "Content-Type": "application/json",
    //     },
    //   }
    // );

    // const json = await res.json();
    let json: { tracks: Song[] } = {
      tracks: [
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/4F7Q5NV6h5TSwCainz8S5A",
                },
                href: "https://api.spotify.com/v1/artists/4F7Q5NV6h5TSwCainz8S5A",
                id: "4F7Q5NV6h5TSwCainz8S5A",
                name: "Duke Ellington",
                type: "artist",
                uri: "spotify:artist:4F7Q5NV6h5TSwCainz8S5A",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/65j8DZA5kEu6QfsFL4vmOv",
            },
            href: "https://api.spotify.com/v1/albums/65j8DZA5kEu6QfsFL4vmOv",
            id: "65j8DZA5kEu6QfsFL4vmOv",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273386604f42be1dcc162639114",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02386604f42be1dcc162639114",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851386604f42be1dcc162639114",
                width: 64,
              },
            ],
            name: "Early Ellington: The Complete Brunswick And Vocalion Recordings 1926-1931",
            release_date: "1994-01-01",
            release_date_precision: "day",
            total_tracks: 67,
            type: "album",
            uri: "spotify:album:65j8DZA5kEu6QfsFL4vmOv",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5FDQAcoLHvQkpAlrwWky3i",
              },
              href: "https://api.spotify.com/v1/artists/5FDQAcoLHvQkpAlrwWky3i",
              id: "5FDQAcoLHvQkpAlrwWky3i",
              name: "Duke Ellington & His Cotton Club Orchestra",
              type: "artist",
              uri: "spotify:artist:5FDQAcoLHvQkpAlrwWky3i",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 166600,
          explicit: false,
          external_ids: {
            isrc: "USMC13027091",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/02ayxdQSSQRIWBLWuZwi4u",
          },
          href: "https://api.spotify.com/v1/tracks/02ayxdQSSQRIWBLWuZwi4u",
          id: "02ayxdQSSQRIWBLWuZwi4u",
          is_local: false,
          name: "Jubilee Stomp",
          popularity: 24,
          preview_url:
            "https://p.scdn.co/mp3-preview/f48265e9ddf1707d860bd89a43596aca521498a9?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 15,
          type: "track",
          uri: "spotify:track:02ayxdQSSQRIWBLWuZwi4u",
        },
        {
          album: {
            album_type: "COMPILATION",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/1pBuKaLHJlIlqYxQQaflve",
                },
                href: "https://api.spotify.com/v1/artists/1pBuKaLHJlIlqYxQQaflve",
                id: "1pBuKaLHJlIlqYxQQaflve",
                name: "Benny Goodman",
                type: "artist",
                uri: "spotify:artist:1pBuKaLHJlIlqYxQQaflve",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/1I1E1ZUYFDK0Dn4DK5YmrH",
            },
            href: "https://api.spotify.com/v1/albums/1I1E1ZUYFDK0Dn4DK5YmrH",
            id: "1I1E1ZUYFDK0Dn4DK5YmrH",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273786965f18ad7960240020a43",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02786965f18ad7960240020a43",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851786965f18ad7960240020a43",
                width: 64,
              },
            ],
            name: "The Best Of Benny Goodman",
            release_date: "1997-01-01",
            release_date_precision: "day",
            total_tracks: 18,
            type: "album",
            uri: "spotify:album:1I1E1ZUYFDK0Dn4DK5YmrH",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1pBuKaLHJlIlqYxQQaflve",
              },
              href: "https://api.spotify.com/v1/artists/1pBuKaLHJlIlqYxQQaflve",
              id: "1pBuKaLHJlIlqYxQQaflve",
              name: "Benny Goodman",
              type: "artist",
              uri: "spotify:artist:1pBuKaLHJlIlqYxQQaflve",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 179840,
          explicit: false,
          external_ids: {
            isrc: "USCA29701307",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/5TjO0GOOon3R6YOnRFPwzk",
          },
          href: "https://api.spotify.com/v1/tracks/5TjO0GOOon3R6YOnRFPwzk",
          id: "5TjO0GOOon3R6YOnRFPwzk",
          is_local: false,
          name: "Chicago",
          popularity: 54,
          preview_url:
            "https://p.scdn.co/mp3-preview/2b620db2608e39833961c968a4c9dc35b1b9b303?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 8,
          type: "track",
          uri: "spotify:track:5TjO0GOOon3R6YOnRFPwzk",
        },
        {
          album: {
            album_type: "SINGLE",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5XMyhVhi5ZN2pi0Qwi1zXS",
                },
                href: "https://api.spotify.com/v1/artists/5XMyhVhi5ZN2pi0Qwi1zXS",
                id: "5XMyhVhi5ZN2pi0Qwi1zXS",
                name: "Joy Crookes",
                type: "artist",
                uri: "spotify:artist:5XMyhVhi5ZN2pi0Qwi1zXS",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5UoWl95U6YTsS1N6JyQ7j4",
            },
            href: "https://api.spotify.com/v1/albums/5UoWl95U6YTsS1N6JyQ7j4",
            id: "5UoWl95U6YTsS1N6JyQ7j4",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2738f5b10774f455be8c7b930c6",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e028f5b10774f455be8c7b930c6",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048518f5b10774f455be8c7b930c6",
                width: 64,
              },
            ],
            name: "Perception EP",
            release_date: "2019-05-31",
            release_date_precision: "day",
            total_tracks: 5,
            type: "album",
            uri: "spotify:album:5UoWl95U6YTsS1N6JyQ7j4",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5XMyhVhi5ZN2pi0Qwi1zXS",
              },
              href: "https://api.spotify.com/v1/artists/5XMyhVhi5ZN2pi0Qwi1zXS",
              id: "5XMyhVhi5ZN2pi0Qwi1zXS",
              name: "Joy Crookes",
              type: "artist",
              uri: "spotify:artist:5XMyhVhi5ZN2pi0Qwi1zXS",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 131097,
          explicit: false,
          external_ids: {
            isrc: "GBARL1900585",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/0gZcAOhjbDoLGzCQ0VW2J6",
          },
          href: "https://api.spotify.com/v1/tracks/0gZcAOhjbDoLGzCQ0VW2J6",
          id: "0gZcAOhjbDoLGzCQ0VW2J6",
          is_local: false,
          name: "No Hands",
          popularity: 57,
          preview_url:
            "https://p.scdn.co/mp3-preview/24b701da9109b9dfcc65986badd2885c9f45aaa8?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 2,
          type: "track",
          uri: "spotify:track:0gZcAOhjbDoLGzCQ0VW2J6",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/4WoGga7UeRcmjD4ufif4nG",
                },
                href: "https://api.spotify.com/v1/artists/4WoGga7UeRcmjD4ufif4nG",
                id: "4WoGga7UeRcmjD4ufif4nG",
                name: "Tommy Dorsey",
                type: "artist",
                uri: "spotify:artist:4WoGga7UeRcmjD4ufif4nG",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/6mcP2ZPyrpMIOrXvSDNQ3g",
            },
            href: "https://api.spotify.com/v1/albums/6mcP2ZPyrpMIOrXvSDNQ3g",
            id: "6mcP2ZPyrpMIOrXvSDNQ3g",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2739675ba265c48533a19c64cbf",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e029675ba265c48533a19c64cbf",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048519675ba265c48533a19c64cbf",
                width: 64,
              },
            ],
            name: "The Essential Frank Sinatra with the Tommy Dorsey Orchestra (with Frank Sinatra)",
            release_date: "2005-09-19",
            release_date_precision: "day",
            total_tracks: 44,
            type: "album",
            uri: "spotify:album:6mcP2ZPyrpMIOrXvSDNQ3g",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4WoGga7UeRcmjD4ufif4nG",
              },
              href: "https://api.spotify.com/v1/artists/4WoGga7UeRcmjD4ufif4nG",
              id: "4WoGga7UeRcmjD4ufif4nG",
              name: "Tommy Dorsey",
              type: "artist",
              uri: "spotify:artist:4WoGga7UeRcmjD4ufif4nG",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1Mxqyy3pSjf8kZZL4QVxS0",
              },
              href: "https://api.spotify.com/v1/artists/1Mxqyy3pSjf8kZZL4QVxS0",
              id: "1Mxqyy3pSjf8kZZL4QVxS0",
              name: "Frank Sinatra",
              type: "artist",
              uri: "spotify:artist:1Mxqyy3pSjf8kZZL4QVxS0",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 195346,
          explicit: false,
          external_ids: {
            isrc: "USBB18801054",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/0iDwZ5rqQvefGEDuiZnuSr",
          },
          href: "https://api.spotify.com/v1/tracks/0iDwZ5rqQvefGEDuiZnuSr",
          id: "0iDwZ5rqQvefGEDuiZnuSr",
          is_local: false,
          name: "Oh! Look at Me Now (with Frank Sinatra)",
          popularity: 31,
          preview_url:
            "https://p.scdn.co/mp3-preview/b7da2b9fd78e9c1ed5f6e2edb9b0358124d8e8d3?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 19,
          type: "track",
          uri: "spotify:track:0iDwZ5rqQvefGEDuiZnuSr",
        },
        {
          album: {
            album_type: "SINGLE",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/6hV6oxGLeLFw17DGjIPkYD",
                },
                href: "https://api.spotify.com/v1/artists/6hV6oxGLeLFw17DGjIPkYD",
                id: "6hV6oxGLeLFw17DGjIPkYD",
                name: "Cosmo Sheldrake",
                type: "artist",
                uri: "spotify:artist:6hV6oxGLeLFw17DGjIPkYD",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/68EgFGec3MQNIikSow8y5Y",
            },
            href: "https://api.spotify.com/v1/albums/68EgFGec3MQNIikSow8y5Y",
            id: "68EgFGec3MQNIikSow8y5Y",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2737b09880ab897baf48521522a",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e027b09880ab897baf48521522a",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048517b09880ab897baf48521522a",
                width: 64,
              },
            ],
            name: "No. 3",
            release_date: "2022-03-08",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:68EgFGec3MQNIikSow8y5Y",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/6hV6oxGLeLFw17DGjIPkYD",
              },
              href: "https://api.spotify.com/v1/artists/6hV6oxGLeLFw17DGjIPkYD",
              id: "6hV6oxGLeLFw17DGjIPkYD",
              name: "Cosmo Sheldrake",
              type: "artist",
              uri: "spotify:artist:6hV6oxGLeLFw17DGjIPkYD",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 190205,
          explicit: false,
          external_ids: {
            isrc: "GBKPL2286667",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/3JQnsBUy7GintnWAwapwEY",
          },
          href: "https://api.spotify.com/v1/tracks/3JQnsBUy7GintnWAwapwEY",
          id: "3JQnsBUy7GintnWAwapwEY",
          is_local: false,
          name: "No. 3",
          popularity: 53,
          preview_url:
            "https://p.scdn.co/mp3-preview/84ccc4a3dd3029159f7f6c4883fa583876b1e96b?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 1,
          type: "track",
          uri: "spotify:track:3JQnsBUy7GintnWAwapwEY",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/3rxeQlsv0Sc2nyYaZ5W71T",
                },
                href: "https://api.spotify.com/v1/artists/3rxeQlsv0Sc2nyYaZ5W71T",
                id: "3rxeQlsv0Sc2nyYaZ5W71T",
                name: "Chet Baker",
                type: "artist",
                uri: "spotify:artist:3rxeQlsv0Sc2nyYaZ5W71T",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5JJ779nrbHx0KB2lBrMMa4",
            },
            href: "https://api.spotify.com/v1/albums/5JJ779nrbHx0KB2lBrMMa4",
            id: "5JJ779nrbHx0KB2lBrMMa4",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273bcaf6f097b310e20504f2de0",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02bcaf6f097b310e20504f2de0",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851bcaf6f097b310e20504f2de0",
                width: 64,
              },
            ],
            name: "Chet Baker Sings",
            release_date: "1956",
            release_date_precision: "year",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:5JJ779nrbHx0KB2lBrMMa4",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3rxeQlsv0Sc2nyYaZ5W71T",
              },
              href: "https://api.spotify.com/v1/artists/3rxeQlsv0Sc2nyYaZ5W71T",
              id: "3rxeQlsv0Sc2nyYaZ5W71T",
              name: "Chet Baker",
              type: "artist",
              uri: "spotify:artist:3rxeQlsv0Sc2nyYaZ5W71T",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 215466,
          explicit: false,
          external_ids: {
            isrc: "USBN28900078",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/06UkYE0SZ3Y8zGRFOuWGAe",
          },
          href: "https://api.spotify.com/v1/tracks/06UkYE0SZ3Y8zGRFOuWGAe",
          id: "06UkYE0SZ3Y8zGRFOuWGAe",
          is_local: false,
          name: "It's Always You - Vocal Version",
          popularity: 63,
          preview_url:
            "https://p.scdn.co/mp3-preview/245354fa587b4140f3e287f40be5ad7c6f1a80f8?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 2,
          type: "track",
          uri: "spotify:track:06UkYE0SZ3Y8zGRFOuWGAe",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5j4HeCoUlzhfWtjAfM1acR",
                },
                href: "https://api.spotify.com/v1/artists/5j4HeCoUlzhfWtjAfM1acR",
                id: "5j4HeCoUlzhfWtjAfM1acR",
                name: "Stromae",
                type: "artist",
                uri: "spotify:artist:5j4HeCoUlzhfWtjAfM1acR",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5JY3b9cELQsoG7D5TJMOgw",
            },
            href: "https://api.spotify.com/v1/albums/5JY3b9cELQsoG7D5TJMOgw",
            id: "5JY3b9cELQsoG7D5TJMOgw",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b27331d6b27ffaa0b2f89234698a",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e0231d6b27ffaa0b2f89234698a",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d0000485131d6b27ffaa0b2f89234698a",
                width: 64,
              },
            ],
            name: "Multitude",
            release_date: "2022-03-03",
            release_date_precision: "day",
            total_tracks: 12,
            type: "album",
            uri: "spotify:album:5JY3b9cELQsoG7D5TJMOgw",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5j4HeCoUlzhfWtjAfM1acR",
              },
              href: "https://api.spotify.com/v1/artists/5j4HeCoUlzhfWtjAfM1acR",
              id: "5j4HeCoUlzhfWtjAfM1acR",
              name: "Stromae",
              type: "artist",
              uri: "spotify:artist:5j4HeCoUlzhfWtjAfM1acR",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 125706,
          explicit: false,
          external_ids: {
            isrc: "BET672100002",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/2GiZ3sC2p1Cc2t2gbdMKsN",
          },
          href: "https://api.spotify.com/v1/tracks/2GiZ3sC2p1Cc2t2gbdMKsN",
          id: "2GiZ3sC2p1Cc2t2gbdMKsN",
          is_local: false,
          name: "Invaincu",
          popularity: 77,
          preview_url:
            "https://p.scdn.co/mp3-preview/8d5aa5badc20ac5eee91f2e16a41eedf25b3b960?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 1,
          type: "track",
          uri: "spotify:track:2GiZ3sC2p1Cc2t2gbdMKsN",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/3JUUs8oZ6MRA1f2ahfusYu",
                },
                href: "https://api.spotify.com/v1/artists/3JUUs8oZ6MRA1f2ahfusYu",
                id: "3JUUs8oZ6MRA1f2ahfusYu",
                name: "Roseaux",
                type: "artist",
                uri: "spotify:artist:3JUUs8oZ6MRA1f2ahfusYu",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5LY0M7xf1d8Xe8b0LOydPu",
            },
            href: "https://api.spotify.com/v1/albums/5LY0M7xf1d8Xe8b0LOydPu",
            id: "5LY0M7xf1d8Xe8b0LOydPu",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273bb174404fed460e21ecebf4f",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02bb174404fed460e21ecebf4f",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851bb174404fed460e21ecebf4f",
                width: 64,
              },
            ],
            name: "Roseaux II",
            release_date: "2019-09-06",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:5LY0M7xf1d8Xe8b0LOydPu",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3JUUs8oZ6MRA1f2ahfusYu",
              },
              href: "https://api.spotify.com/v1/artists/3JUUs8oZ6MRA1f2ahfusYu",
              id: "3JUUs8oZ6MRA1f2ahfusYu",
              name: "Roseaux",
              type: "artist",
              uri: "spotify:artist:3JUUs8oZ6MRA1f2ahfusYu",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/0QnqZZKkxzvl9bnSJnoV8E",
              },
              href: "https://api.spotify.com/v1/artists/0QnqZZKkxzvl9bnSJnoV8E",
              id: "0QnqZZKkxzvl9bnSJnoV8E",
              name: "Blick Bassy",
              type: "artist",
              uri: "spotify:artist:0QnqZZKkxzvl9bnSJnoV8E",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 247237,
          explicit: false,
          external_ids: {
            isrc: "FR6DF1800001",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/3poi95CMNu7G9h0q4qOxl3",
          },
          href: "https://api.spotify.com/v1/tracks/3poi95CMNu7G9h0q4qOxl3",
          id: "3poi95CMNu7G9h0q4qOxl3",
          is_local: false,
          name: "Kaät",
          popularity: 57,
          preview_url:
            "https://p.scdn.co/mp3-preview/91e55618e7d69b516607cd776f0c7e8d69606483?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 1,
          type: "track",
          uri: "spotify:track:3poi95CMNu7G9h0q4qOxl3",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5P0unmRK5EI6psA51571i7",
                },
                href: "https://api.spotify.com/v1/artists/5P0unmRK5EI6psA51571i7",
                id: "5P0unmRK5EI6psA51571i7",
                name: "Woody and Jeremy",
                type: "artist",
                uri: "spotify:artist:5P0unmRK5EI6psA51571i7",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/7asSXczPSP1MDGaeFLkHmH",
            },
            href: "https://api.spotify.com/v1/albums/7asSXczPSP1MDGaeFLkHmH",
            id: "7asSXczPSP1MDGaeFLkHmH",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273ff6d51abab463e7ce977122d",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02ff6d51abab463e7ce977122d",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851ff6d51abab463e7ce977122d",
                width: 64,
              },
            ],
            name: "Strange Satisfaction",
            release_date: "2020-03-13",
            release_date_precision: "day",
            total_tracks: 7,
            type: "album",
            uri: "spotify:album:7asSXczPSP1MDGaeFLkHmH",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5P0unmRK5EI6psA51571i7",
              },
              href: "https://api.spotify.com/v1/artists/5P0unmRK5EI6psA51571i7",
              id: "5P0unmRK5EI6psA51571i7",
              name: "Woody and Jeremy",
              type: "artist",
              uri: "spotify:artist:5P0unmRK5EI6psA51571i7",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 1,
          duration_ms: 256440,
          explicit: false,
          external_ids: {
            isrc: "QZFZ22027400",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/2IB1LWbNli57u0k7U1GAXt",
          },
          href: "https://api.spotify.com/v1/tracks/2IB1LWbNli57u0k7U1GAXt",
          id: "2IB1LWbNli57u0k7U1GAXt",
          is_local: false,
          name: "Too Hot in L.A.",
          popularity: 48,
          preview_url:
            "https://p.scdn.co/mp3-preview/14b80a45b9dc08158cbd6506056da9dc29b8e650?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 1,
          type: "track",
          uri: "spotify:track:2IB1LWbNli57u0k7U1GAXt",
        },
        {
          album: {
            album_type: "ALBUM",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5RzjqfPS0Bu4bUMkyNNDpn",
                },
                href: "https://api.spotify.com/v1/artists/5RzjqfPS0Bu4bUMkyNNDpn",
                id: "5RzjqfPS0Bu4bUMkyNNDpn",
                name: "Dizzy Gillespie",
                type: "artist",
                uri: "spotify:artist:5RzjqfPS0Bu4bUMkyNNDpn",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5DGcQGe6AvE5LGdYyZlHfn",
            },
            href: "https://api.spotify.com/v1/albums/5DGcQGe6AvE5LGdYyZlHfn",
            id: "5DGcQGe6AvE5LGdYyZlHfn",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2732cd31f4139e3886f1f4e863f",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e022cd31f4139e3886f1f4e863f",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048512cd31f4139e3886f1f4e863f",
                width: 64,
              },
            ],
            name: "Dizzy 100",
            release_date: "2017-09-29",
            release_date_precision: "day",
            total_tracks: 100,
            type: "album",
            uri: "spotify:album:5DGcQGe6AvE5LGdYyZlHfn",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5RzjqfPS0Bu4bUMkyNNDpn",
              },
              href: "https://api.spotify.com/v1/artists/5RzjqfPS0Bu4bUMkyNNDpn",
              id: "5RzjqfPS0Bu4bUMkyNNDpn",
              name: "Dizzy Gillespie",
              type: "artist",
              uri: "spotify:artist:5RzjqfPS0Bu4bUMkyNNDpn",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/217b0uqAzsOOhGcnoANZqj",
              },
              href: "https://api.spotify.com/v1/artists/217b0uqAzsOOhGcnoANZqj",
              id: "217b0uqAzsOOhGcnoANZqj",
              name: "Sonny Stitt",
              type: "artist",
              uri: "spotify:artist:217b0uqAzsOOhGcnoANZqj",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1VEzN9lxvG6KPR3QQGsebR",
              },
              href: "https://api.spotify.com/v1/artists/1VEzN9lxvG6KPR3QQGsebR",
              id: "1VEzN9lxvG6KPR3QQGsebR",
              name: "Sonny Rollins",
              type: "artist",
              uri: "spotify:artist:1VEzN9lxvG6KPR3QQGsebR",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA",
          ],
          disc_number: 3,
          duration_ms: 342891,
          explicit: false,
          external_ids: {
            isrc: "USPR35702495",
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/38R2EViAkYOFG8ZkG3GLtW",
          },
          href: "https://api.spotify.com/v1/tracks/38R2EViAkYOFG8ZkG3GLtW",
          id: "38R2EViAkYOFG8ZkG3GLtW",
          is_local: false,
          name: "On The Sunny Side Of The Street",
          popularity: 57,
          preview_url:
            "https://p.scdn.co/mp3-preview/c3e1b9c3130538838146a4dda33f2d583adda296?cid=c5a214426a734ca98c09946adfd20c3a",
          track_number: 3,
          type: "track",
          uri: "spotify:track:38R2EViAkYOFG8ZkG3GLtW",
        },
      ],
    };
    setCards(
      cards.length > 0
        ? [...cards, ...json.tracks.filter((card) => card.id != cards[0].id)]
        : [...json.tracks]
    );
  };

  useEffect(() => {
    if (cards.length <= 1)
      setTimeout(() => {
        getSong();
      }, 300);
  }, [cards]);

  return (
    <>
      <Container className="App">
        {cards.map((card, index) => (
          <Swipable
            key={card.id}
            index={index}
            onTrigger={dequeue}
            triggerDelay={300}
          >
            <SongCard currentSong={card} isOnTop={index == 0} />
          </Swipable>
        ))}
      </Container>
    </>
  );
}

//https://api.spotify.com/v1/tracks/3JcFxUFb4ksMUaAM5LscUb
//3JcFxUFb4ksMUaAM5LscUb
